### ISSUE TITLE
is the $inject property a "public" API?

### ISSUE THREAD

**Issue by artoale** [vojtajina/node-di#7]
Hi!
I'm about to write some code that has to run both on node and in the browser, and I really want to use some DI system. I've already used node-di and I like it, I think it's easier to use (because of it's explicit dependency declaration) w.r.t. wire.js, and I'd really go for that solution...and - as far as I can see - there should be no problem in running node-di in a browser. 
The only caveat is about the inline-comment, since they would be stripped out when minified (much like the same issue in angular, solved by the [] notation).

Can I relay on the $inject array, or this is not considered a public API and can likely with time?

Many thanks

**Comment by vojtajina** [comment]
@artoale I'm sorry for such a delay, somehow I disabled notifications for this project and missed all the issues/PRs.

The `$inject` might be considered a public API. It's not gonna change - if you define `$inject` property, it will be used instead of parsing the function string.

That said, I don't actively maintain this project anymore, in favor of https://github.com/angular/di.js which is designed to run both in Node and browser. It powers the upcoming Angular v2. It is heavily influenced by this project and so I think it should be pretty straightforward to migrate.

**Comment by artoale** [comment]
@vojtajina - no problem at all, I'm already considering angular DI (this is how I originally found your project :) ) Cheers!
